CREATE DATABASE IF NOT EXISTS stats;

USE stats;

CREATE TABLE stat (
  id BIGINT AUTO_INCREMENT,
  dat DATE NOT NULL,
  clicks INT DEFAULT NULL,
  cost INT DEFAULT NULL,
  views INT DEFAULT NULL,
  PRIMARY KEY(id)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;