server:
  host: localhost
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5

db:
  user: pavel
  password: pavel
  proto: tcp
  host: localhost
  port: 3306
  dbname: stats